export const tasks = [
  {
    id: 1,
    title: "Buy groceries",
    description: "Milk, eggs, bread, apples",
    completed: false,
    priority: "urgent",
    dueDate: "2025-09-01",
    pomodoros: 2,
    category: "Personal",
  },
  {
    id: 2,
    title: "Workout",
    description: "Strength training: chest and back",
    completed: false,
    priority: "important",
    dueDate: "2025-09-02",
    pomodoros: 3,
    category: "Health",
  },
  {
    id: 3,
    title: "Read a book",
    description: "Finish chapter 5",
    completed: true,
    priority: "later",
    dueDate: "2025-08-28",
    pomodoros: 1,
    category: "Leisure",
  },
  {
    id: 4,
    title: "Build project",
    description: "Setup tsconfig and check eslint",
    completed: false,
    priority: "urgent",
    dueDate: "2025-08-30",
    pomodoros: 4,
    category: "Work",
  },
  {
    id: 5,
    title: "Call client",
    description: "Discuss project changes",
    completed: false,
    priority: "important",
    dueDate: "2025-08-29",
    pomodoros: 2,
    category: "Work",
  },
];
